# Generated by Django 4.0.2 on 2022-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koochooloo',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='koochooloo',
            name='pashiz',
            field=models.FloatField(default=0),
        ),
    ]
